### ISSUE TITLE
UTF-8 in socialUrls

### ISSUE THREAD

**Issue by rendonvelez** [DanielHabenicht/ngx-vcard#205]
in socialUrls urls are not visible when the econding is UTF-8

**Comment by DanielHabenicht** [comment]
Can you post a code snippet on what you are using?

**Comment by DanielHabenicht** [comment]
Without an reproduction I can't fix the bug.

**Comment by DanielHabenicht** [comment]
Closing because of missing reproduction. Also seems to be tracked partly here #36.
