### ISSUE TITLE
How can use VCardFormatter functions ?

### ISSUE THREAD

**Issue by togro** [DanielHabenicht/ngx-vcard#292]
Hi , 

We want store vCard on database , exists any way for use functions from VCardFormatter module ?

Like : VCardFormatter.getVCardAsString

**Comment by DanielHabenicht** [comment]
I added it to the public API `VCardFormatter` should now be able to be imported. 
(as of version 2.1.0)

**Comment by DanielHabenicht** [comment]
You can also have a look at the example: https://stackblitz.com/github/DanielHabenicht/ngx-vcard
