### ISSUE TITLE
telephone value is not showing in generated card 

### ISSUE THREAD

**Issue by nileshzala005** [DanielHabenicht/ngx-vcard#321]
I set telephone value in card but when I download the vcard , its not showing telephone value . let me know if there is another way to set mobile number or telephone value 
Please check this [stackblitz](https://stackblitz.com/edit/github-ghytqv)
 ```
public vCardEncoding: typeof VCardEncoding = VCardEncoding;
  public vCard: VCard = { name: { firstNames: 'John', lastNames: 'Doe' },telephone:['+919825098250'] };
  public vCardString = VCardFormatter.getVCardAsString(this.vCard)
```
![image](https://user-images.githubusercontent.com/28622981/88058426-157db100-cb81-11ea-96ab-4e3cf052f471.png)

**Comment by DanielHabenicht** [comment]
seems like the type is not set automatically. You can use the following "workaround" till I will fix it: 

```typescript
public vCard: VCard = { name: { firstNames: 'John', lastNames: 'Doe' },telephone:[{
    value: '+919825098250', 
    param: {
      type: 'cell'
    }}] };
```

**Comment by nileshzala005** [comment]
@DanielHabenicht still its not working ,https://stackblitz.com/edit/github-ghytqv

**Comment by Blindworks** [comment]
Hi, it also seems like that the type param in address is not working properly.

`this.vCard = {
      version: '4.0',
      kind: 'individual',
      address: [
        { street: this.foundPrivateAddress.street,
          locality: this.foundPrivateAddress.city,
          countryName: this.foundPrivateAddress.country,
          postalCode: this.foundPrivateAddress.zip,
          param: {
            type:'home',
          },
        },
        { street: this.foundEmployerAddress.street,
          locality: this.foundEmployerAddress.city,
          countryName: this.foundEmployerAddress.country,
          postalCode: this.foundEmployerAddress.zip,
          param: {
            type: 'work',
          }
        }
      ],`

leads to empty Type in vcf file.

**Comment by DanielHabenicht** [comment]
@Blindworks can you please open another issue with reproduction, as @nileshzala005 send for this issue? (via Stackblitz). 
I couldn't reproduce your error: https://stackblitz.com/edit/github-ghytqv-57dyhj?file=src/app/app.component.ts

Telephone value will be visible with the next update, the default type will be `voice` as stated by the [RFC](https://tools.ietf.org/html/rfc6350#section-6.4.1).
