### ISSUE TITLE
Error en Chrome/Edge IOS/Android

### ISSUE THREAD

**Issue by DIKGONZA** [DanielHabenicht/ngx-vcard#420]
Hola buen día

Estoy usando el servicio pero en IOS al darle clic en el botón no descarga nada cuando la pagina se abre por chrome v87 ni por edge, por safari si lo descarga.

y en android saca error al descargar e intentar leer el archivo, dice que no se puede leer la tarjeta.

**Comment by DanielHabenicht** [comment]
Sry, but this is an English issue tracker. Can you please write in English?

**Comment by DanielHabenicht** [comment]
Closed because of inactivity, feel free to create an issue in english and with a reproduction.
