### ISSUE TITLE
Telephone not working in Apple Contacts

### ISSUE THREAD

**Issue by lasserg** [DanielHabenicht/ngx-vcard#427]
I have a problem with the plugin. 
When adding a phone number it does not show up in Mac OS address book. 
The code is as following:
`this.vCard = {
                name: {
                    firstNames: this.person.first_name,
                    lastNames: this.person.last_name
                },
                telephone: [this.person.cell_phone],
                email: [this.person.email]
            };`

I have tried defining type on the phone number also, but that doesn't work either.

**Comment by DanielHabenicht** [comment]
I don't have an iPhone, so I can't reproduce. 

Can you export a VCard from Apple Contacts and paste the file here?
