### ISSUE TITLE
Rename homepage to website

### ISSUE THREAD

**Issue by faizaldong** [DanielHabenicht/ngx-vcard#433]
Hi Maintainer.

Do we have an option to change the attribute of VCard? In my codes I have
        url: {
            home: https://github.com/DanielHabenicht/ngx-vcard/issues/new,
            work: https://github.com/DanielHabenicht/ngx-vcard/issues/new
        },

but after export, Vcard have duplicate home page

![vcard](https://user-images.githubusercontent.com/17352624/106406171-70b72700-6473-11eb-9916-8b06d9d0a5d3.png)

**Comment by DanielHabenicht** [comment]
Hi @faizaldong ,

there is indeed a bug withing the formatter, which specifies both as `work` type. 
https://github.com/DanielHabenicht/ngx-vcard/blob/1444eb5a4dd179945923e05f8c101c48e360cd1e/projects/ngx-vcard/src/lib/ngx-vcard.formatter.ts#L190-L204

But as the [RFC Documentation](https://tools.ietf.org/html/rfc6350#section-6.7.8) does not has an option for naming the link, there is none implemented. 

Either way it seems like it is possible: https://www.w3.org/2002/12/cal/vcard-notes.html
If you want you can implement it.

**Comment by faizaldong** [comment]
> Hi @faizaldong ,
> 
> there is indeed a bug within the formatter, which specifies both as `work` type.
> https://github.com/DanielHabenicht/ngx-vcard/blob/1444eb5a4dd179945923e05f8c101c48e360cd1e/projects/ngx-vcard/src/lib/ngx-vcard.formatter.ts#L190-L204
> 
> But as the [RFC Documentation](https://tools.ietf.org/html/rfc6350#section-6.7.8) does not has an option for naming the link, there is none implemented.
> 
> Either way it seems like it is possible: https://www.w3.org/2002/12/cal/vcard-notes.html
> If you want you can implement it.

So after your changes, will remove the duplicate `home page` ? 
reinstalled your library and the duplicate still appear

**Comment by DanielHabenicht** [comment]
Yep, but that depends on the App you are using. 
It is not guaranteed :/

**Comment by DanielHabenicht** [comment]
Even the link I referenced as the solution does not help: 
![image](https://user-images.githubusercontent.com/13590797/107267676-86b28200-6a47-11eb-876c-b8da5e06aa51.png)
If the program that displays the card overwrites the label for you want to be displayed, you can't change it.
