### ISSUE TITLE
Please make it work for angular 11.2.10

### ISSUE THREAD

**Issue by UnChallenged** [DanielHabenicht/ngx-vcard#476]
getting this dependencies issues while installing

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: bizcard@0.0.0
npm ERR! Found: @angular/common@11.2.10
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"11.2.10" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=5.x <11.0.0" from ngx-vcard@3.0.20
npm ERR! node_modules/ngx-vcard
npm ERR!   ngx-vcard@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by DanielHabenicht** [comment]
can you try it with force? and report back if everything works? 

Then I will upgrade the version number

**Comment by UnChallenged** [comment]
Thank you. with --force it works.

**Comment by DanielHabenicht** [comment]
yeah, that's just a workaround. I will add the higher version.

**Comment by DanielHabenicht** [comment]
Should be fixed by #540
