### ISSUE TITLE
Download in Internet Explorer does not work

### ISSUE THREAD

**Issue by FelsGorilla** [DanielHabenicht/ngx-vcard#5]
Hi, 

i'm trying to get it work in Internet Explorer. Sadly Edge just does nothing, whilst IE 11 is erroring with "ERROR TypeError: Die Zuordnung zu schreibgeschützten Eigenschaften ist im strict-Modus nicht zulässig.".

I'm using Angular 6, error appears on prod and dev build.

**Comment by DanielHabenicht** [comment]
Hi, 
I did not had time yet to test in every browser, so thanks for reporting.

It should be fixed in the next update (v1.1.3).
