### ISSUE TITLE
Angular 12 Support

### ISSUE THREAD

**Issue by bkr32** [DanielHabenicht/ngx-vcard#540]
The current version of `ngx-vcard` supports Angular 11, please bring it up to support Angular 12

**Comment by maxbauer** [comment]
For me it works with Angular12 as well

**Comment by bkr32** [comment]
@maxbauer did you happened to do `--force` or `--legacy-deps` while installing?

**Comment by maxbauer** [comment]
Hmm, I do not remember that. I think I just installed it with `npm i ngx-vcard`

**Comment by DanielHabenicht** [comment]
Is it working with angular 1? Then I will just increase the package version for now and update the framework later

**Comment by bkr32** [comment]
@DanielHabenicht the error given when attempting to install with angular 12 is
```
npm ERR!   @angular/common@"^12.1.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=5.x <11.0.0" from ngx-vcard@3.0.22
```

**Comment by DanielHabenicht** [comment]
I know, but if you force it and use it then is it working?

**Comment by bkr32** [comment]
@DanielHabenicht yes it seems to work fine using `--force` this was tested using the directive and not the formatter however

**Comment by bkr32** [comment]
@DanielHabenicht not to be a bother but the error still occurs on sub-versions greater than `12.0.0` 

`npm i ngx-vcard@latest`



```
npm ERR! Found: @angular/common@12.2.2
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^12.1.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=5.x <12.0.0" from ngx-vcard@3.0.23
npm ERR! node_modules/ngx-vcard
npm ERR!   ngx-vcard@"3.0.23" from the root project
```

of course no real issue in terms of installing and using with `--force`

**Comment by DanielHabenicht** [comment]
Yep didn't thought that there are already 2 new versions 😅
I will fix it soon
