### ISSUE TITLE
Download button not working on iOS with Firefox

### ISSUE THREAD

**Issue by maxbauer** [DanielHabenicht/ngx-vcard#551]
Thanks in advance for this nice vCard library. I included it in my project and found the following bug:
Download button is not working with Firefox on iOS

**Steps to reproduce**
1. Open the Stackblitz example: https://stackblitz.com/github/DanielHabenicht/ngx-vcard
2. When clicking on the "Download VCard!" button nothing happens

**Environment**
- iPhone with iOS 14.7.1 
- Firefox 36.0 (5732)

**Comment by danielsigl** [comment]
Same for Chrome on iOS

**Comment by DanielHabenicht** [comment]
Did one of you already implement a workaround? E.g. by using file-saver package? (See #89)

Just asking on how to go forward on this. I don't want to maintain the download functionality as this is already done by multiple other packages. 

So I might repackage it into a formater package (without dependencies) and another one with the directive (depending on one of the download packages).

**Comment by DanielHabenicht** [comment]
@danielsigl can you explain if you are against using another package (https://www.npmjs.com/package/file-saver) or against repackaging?

**Comment by danielsigl** [comment]
Sadly it do not work with file-saver too.

**Comment by DanielHabenicht** [comment]
Then it might be an OS problem, any Errors or Traces in the console?
