### ISSUE TITLE
Validate empty values

### ISSUE THREAD

**Issue by danielsigl** [DanielHabenicht/ngx-vcard#555]
Hi,

It would be very helpful if each value would be checked if empty/null/undefined before adding to the vCard-file. Otherwise the value will be added as [object Object].

TEL;TYPE=voice:[object Object]
EMAIL:[object Object]

Thanks in Advance!

**Comment by danielsigl** [comment]
sorry it was a usage issue ;)

**Comment by danielsigl** [comment]
Hi @DanielHabenicht,

sorry for annoying you, I don't get it.

I'm trying to create an vCard depending on if there is a value or not. 

Is it possible to set each vCard value like that? 

`      if (titleFromForm) {
        this.vCard.title = titleFromForm;
      }`

Thanks in Advance!

Schöne Grüße aus Österreich ;)

**Comment by DanielHabenicht** [comment]
well if it is `undefined` or `null` it should already be checked and not displayed, e.g.: 
https://stackblitz.com/edit/github-9kqggk?file=src/app/app.component.ts 

For your second example: `vCard.address` is not initialized as an array. So you would have to assign it on first use via `vCard.address = [address]` and later use `push()`.

**Comment by danielsigl** [comment]
Thank's for your fast answer! 

In my case, if I try it as in the directive example, undefined and null values are set as [object Object] in the vCard. I have to set them empty ('') that they will be not saved as an object in the android contact

**Comment by DanielHabenicht** [comment]
Can you post a reproduction? 
I can't reproduce: https://stackblitz.com/edit/github-mq7hoj?file=src/app/app.component.ts

**Comment by danielsigl** [comment]
```
this.vCard = {
        telephone: [{
          value: data[0].phone ? data[0].phone : '',
          param: {type: 'work'},
        }, {
          value: data[0].mobile ? data[0].mobile : '',
          param: {type: 'cell'},
        }],
        email: [{
          value: data[0].mail ? data[0].mail : undefined,
          param: {type: 'work'}
        }],
        address: [{
          value: {
            street: data[0].street ? data[0].street : '',
            locality: data[0].locality ? data[0].locality : '',
            postalCode: data[0].postalCode ? data[0].postalCode : '',
            countryName: data[0].country ? data[0].country : '',
          },
          param: {type: 'work'}
        }]
      };
```

**Output:**
```
BEGIN:VCARD
VERSION:4.0
FN:Max Mustermann
N:Mustermann;Max;;;
ORG:Shoptimizer TEST
ADR;TYPE=work:;;Teststraße 21;Testhausen;;5020;Österreich
TEL;TYPE=work:+43676840722822
TEL;TYPE=cell:+436501234567
EMAIL:[object Object]
TITLE:Senior Tester
URL:https://shoptimizer.at
END:VCARD
```

![image](https://user-images.githubusercontent.com/2467358/130508488-ad582eb9-a01d-44b4-8c3a-e98493726444.png)

**Comment by DanielHabenicht** [comment]
I haven't done a reproduction yet. But it seems like it's just happening if you provide the parameter, right?
