### ISSUE TITLE
Add types for telephone and email in the formatter

### ISSUE THREAD

**Issue by bkr32** [DanielHabenicht/ngx-vcard#566]
Telephone numbers  & emails should have types,
for example
 ```
Tel | type | text
Tel | type | voice       
Tel | type | cell
Tel | type | textphone 
```

 ```
email | type | work
email | type | home
email | type | mobile
```

currently we provide phone and email via  array through the formatter which defaults to `other`

**Comment by DanielHabenicht** [comment]
Can you elaborate a little bit? 
You can just provide and object instead of a simple string: 
```typescript
telephone: [{
    value: "+49123456789",
    param: {type: 'work'},
  },
```
